name: mvn-deploy
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3   
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'oracle'                
      - name: Publish package
        env:
          GH_USER: ${{ secrets.BT_USER }}    
          GH_TOKEN: ${{ secrets.BT_TOKEN }}      
        run: mvn  -s .mvn/settings.xml --batch-mode deploy -Dmaven.compiler.parameters=true
